---
# Variable configuration
- name: Include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "vars/{{ ansible_os_family }}.yml"
      skip: true

- name: Define libwebsockets_package
  set_fact:
    libwebsockets_package: "{{ __libwebsockets_package | list }}"
  when: libwebsockets_package is not defined

- name: Define proton_packages
  set_fact:
    proton_packages: "{{ __proton_packages | list }}"
  when: proton_packages is not defined

- name: Define dispatch_packages
  set_fact:
    dispatch_packages: "{{ __dispatch_packages | list }}"
  when: dispatch_packages is not defined

- name: Define dispatch_daemon
  set_fact:
    dispatch_daemon: "{{ __dispatch_daemon }}"
  when: dispatch_daemon is not defined
