---
# Variable configuration
- name: Include OS-specific variables.
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "vars/{{ ansible_os_family }}.yml"
      skip: true

- name: Define dispatch_packages.
  set_fact:
    dispatch_packages: "{{ __dispatch_packages | list }}"
  when: dispatch_packages is not defined
